# This is a basic workflow that is manually triggered

name: Update Formula

# Run when a release is published to update the hombrew formula
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout with actions/checkout@v3 
    - uses: actions/checkout@v3
    - name: download release tarball
    - uses: robinraju/release-downloader@v1.3
      with:
        repo: "OneSignal/cli'"
        tag: "${{ github.ref }}"
        tarBall: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: calculate release tarball sha256
      run: echo "RELEASE_SHA=$(echo openssl sha256 < $GITHUB_WORKSPACE/${{ github.ref }}.tar.gz  )" >> $GITHUB_ENV
    - name: run update_formula.py
      run: python3 ./.github/workflows/update_formula.py ${{ github.ref }} $RELEASE_SHA
    - name: Commit files onesignal-cli.rb
      run: |
        git config --local user.name  ${{ github.actor }}
        git add .
        git commit -m "Updating the onesignal-cli formula for the latest release"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
